### ISSUE TITLE
Subscriptions caching issue with List + Lambda

### ISSUE THREAD

**Issue by gitrojones** [benjie/ouch-my-finger#11]
Hello,

[Here's a fork with reproduction](https://github.com/gitrojones/ouch-my-finger/tree/lambda-list-subscription-cache) of the subscription issue I was running into involving Lambda + List. 

**Setup:**
1. Setup .env, replacing `DATABASE_URL` with your own
2. Setup the schema w/ the `basic-schema.sql` file or equivalent.
3. Run the server via `yarn serve` (Assumes Node20)

**Steps:**
1. Create a subscription in Ruru for Foo
```subscription MySubscription($fooId: Int!) {
  foo(fooId: $fooId) {
    foo {
      createdAt
      fieldToUpdate
      fooId
      id
    }
    event
  }
}
--- VARIABLES
{
  "fooId": 1
}
```
2. Insert a new record into the foo table (assuming id === 1)

**Expectations:**
On insert/update we fetch the latest state of the record.

**Reality:**
We fetch the latest state of the record once, then serve from cache moving forward.

**Why is this a bug?**
If you remove the list from the lambda in `subscribePlan` all works as expected. It's only when a list is supplied that the record seems to be cached. 

**Example of bug:**
![image](https://github.com/benjie/ouch-my-finger/assets/7622528/fdf66a21-2c40-43c2-8536-41a29fd06538)
![image](https://github.com/benjie/ouch-my-finger/assets/7622528/254523a5-74d0-444e-b6f1-6fcc27354479)
![image](https://github.com/benjie/ouch-my-finger/assets/7622528/3e34f46c-dbc6-4a2e-8804-6e5c213f3e33)
![image](https://github.com/benjie/ouch-my-finger/assets/7622528/d7612b70-4332-4af5-ba1b-2680a2abf87c)
![image](https://github.com/benjie/ouch-my-finger/assets/7622528/c3429a67-20fb-4bbf-8346-d596b402ad52)
![image](https://github.com/benjie/ouch-my-finger/assets/7622528/61e274f7-ade1-4b0c-a49d-9482246ff71d)

I did some poking around in the Grafast source but couldn't find anything obvious. Best guess is something to do with the dependency tracking with ListStep and determining safe cache vs unsafe cache. 

Thanks!

**Comment by benjie** [comment]
Issue reproduced.

**Comment by benjie** [comment]
The issue specifically relates to the `context[this.$$cache]` used by PgExecutor not being reset between subscription payloads. This is specifically a bug in PgExecutor, a false assumption about the appropriateness of caching. This cache should also be cleared just before a new mutation field executes.

https://github.com/graphile/crystal/blob/91e87ab6516490a4cc7b7fc6400efb7623fbd331/grafast/dataplan-pg/src/executor.ts#L403

**Comment by benjie** [comment]
Moving discussion to https://github.com/graphile/crystal/issues/2079
