### ISSUE TITLE
Subscription error handling

### ISSUE THREAD

**Issue by gitrojones** [benjie/ouch-my-finger#12]
Hello,

[Here's a fork with reproduction](https://github.com/gitrojones/ouch-my-finger/tree/subscription-error-handling) of the subscription issue I was running into involving error handling. 

**Setup:**
1. Setup .env, replacing `DATABASE_URL` with your own
2. Run the server via `yarn serve` (Assumes Node20)

**Steps:**
1. Create a subscription in Ruru for Foo
```subscription MySubscription($fooId: Int!) {
  foo(fooId: $fooId) {
    event
  }
}
--- VARIABLES
{
  "fooId": 1
}
```

**Expectations:**
The error that is thrown in the subscribePlan should be routed to the maskError where the error can be handled/sanitized like in queries and mutations.

**Reality:**
The error is mishandled and throws an internal error instead. The handler is assuming `originalError` exists in `grafast/prepare.js > output`. 

![image](https://github.com/benjie/ouch-my-finger/assets/7622528/414f15a1-aff8-46d5-8640-133237809ffd)

**Why is this a bug?**
An internal error is unhandled leading to the socket error.

Thanks!

**Comment by benjie** [comment]
Reproduced with

```ts
    makeExtendSchemaPlugin({
      typeDefs: gql`
        extend type Subscription {
          error: Int
        }
      `,
      plans: {
        Subscription: {
          error: {
            subscribePlan() {
              return lambda(constant(3), () => {
                throw new Error("Testing error");
              });
            },
          },
        },
      },
    }),
```

**Comment by benjie** [comment]
Closing in favour of https://github.com/graphile/crystal/issues/2080
