### ISSUE TITLE
Is grafserv missing in package.json?

### ISSUE THREAD

**Issue by EloB** [benjie/ouch-my-finger#5]
Or is that intended?

https://github.com/benjie/ouch-my-finger/blob/main/package.json#L8-L16
https://github.com/benjie/ouch-my-finger/blob/main/server-express.mjs#L3

**Comment by benjie** [comment]
That import should be `from "postgraphile/grafserv/…` - we set up redirects.

**Comment by benjie** [comment]
Fixed in #6
